"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
// import Person from './Person';
var Teacher_1 = require("./Teacher");
var Student_1 = require("./Student");
var Subject_1 = require("./Subject");
var Order_1 = require("./Order");
var OrderItem_1 = require("./OrderItem");
var OrderRepository_1 = require("./OrderRepository");
var carolina = new Student_1.default('Carolina da Silva', new Date('2005/03/17'));
var lucas = new Student_1.default('Lucas Peixoto Salgueiro', new Date('2006/07/19'));
var math = new Subject_1.default('Matemática');
var history = new Subject_1.default('História');
var marta = new Teacher_1.default('Marta da Silva', new Date('1980/03/30'), 2000, math);
var joao = new Teacher_1.default('João Antônio da Costa', new Date('1982/04/21'), 2000, history);
var sandwiche = new OrderItem_1.default('Sandwiche Natural', 5.00);
var juice = new OrderItem_1.default('Suco de Abacaxí', 5.00);
var dessert = new OrderItem_1.default('Gelatina de Uva', 2.50);
var carolinaOrder = new Order_1.default(carolina, [sandwiche, juice, dessert], 'dinheiro', 0.10);
var lucasOrder = new Order_1.default(lucas, [sandwiche, juice], 'dinheiro', 0.10);
var martaOrder = new Order_1.default(marta, [sandwiche, juice], 'cartão');
var joaoOrder = new Order_1.default(joao, [sandwiche, juice, dessert], 'cartão');
var orderRepository = new OrderRepository_1.default();
orderRepository.addOrder(carolinaOrder);
orderRepository.addOrder(lucasOrder);
orderRepository.addOrder(martaOrder);
orderRepository.addOrder(joaoOrder);
orderRepository.addOrder(carolinaOrder);
console.log('Pedidos da Carolina: ', orderRepository.listByClient(carolina));
console.log('Maior valor para o menor: ', orderRepository.listBySortedValue('maior'));
console.log('Menor valor para o maior: ', orderRepository.listBySortedValue('menor'));
